name: WebApi

on:    
  push:

jobs:
  webApi-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo
        run: echo "Hello, World"

      - name: Publish
        run: dotnet publish src/WebApi/WebApi.csproj -c Release -r win-x64 -p:PublishSingleFile=true --output ./publish

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Application_Artifact
          path: ./publish/