name: WebApi

on:    
  push:
    branches: 
      - feature/DCE-156-walking-skeleton
    

jobs:
  webApi-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: dotnet build ./src/WebApi.csproj

      - name: Echo
        run: echo "Hello, World"

      - name: Test
        run: dotnet test ./test

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          node-version: 16
          name: Application_Artifact
          path: /home/runner/work/Artifacts/release/
