name: WebApi

on:    
  push:

jobs:
  webApi-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo
        run: echo "Hello, World"

      - name: Publish
        run: dotnet publish src/WebApi/WebApi.csproj -c Release -r win-x64 -p:PublishSingleFile=true --output ./publish

      - name: Copy README
        run: cp src/WebApi/README.txt ./publish/README.txt  # replace 'README.md' with your actual README file path if it's not in the root directory

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Application_Artifact
          path: |
            ./publish/WebApi.exe
            ./publish/README.md