name: WebApi

on:    
  push:

jobs:
  webApi-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo
        run: echo "Hello, World"
      
      - name: Publish
        run: dotnet publish src/WebApi/WebApi.csproj -r win-x64 -c Release -o release /p:PublishSingleFile=true
    
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy
          path: ./release/WebApi