name: WebApi

on:    
  push:

jobs:
  webApi-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish
        run: dotnet publish src/WebApi/WebApi.csproj -c Release -r win-x64 -p:PublishSingleFile=true --output ./publish

      - name: Copy README
        run: cp src/WebApi/Readme.txt ./publish/Readme.txt

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Application_Artifact
          path: |
            ./publish/WebApi.exe
            ./publish/README.txt