name: WebApi

on:    
  push:

jobs:
  webApi-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo
        run: echo "Hello, World"
      
      - name: Build and Publish
        run: |
          dotnet publish src/WebApi/bin/Release/net6.0/win10-x64/publish/WebApi.exe -c Release -r win-x64 --self-contained true /p:PublishSingleFile=false

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApp
          path: ./release/WebApi