name: WebApi

on:    
  push:

jobs:
  webApi-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo
        run: echo "Hello, World"

      - name: Copy files to workspace
        run: cp ./src/WebApi/bin/Release/net6.0/win10-x64/publish/WebApi.exe ${{ github.workspace }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApp
          path: ${{ github.workspace }}/WebApi.exe